//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using ZocBuild.Database.Application.Settings;
using ZocBuild.Database.ScriptRepositories;

namespace ZocBuild.Database.Application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public List<DatabaseSetting> Databases {
            get {
                return ((List<DatabaseSetting>)(this["Databases"]));
            }
            set {
                this["Databases"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public DvcsScriptRepositoryBase.ChangesetId LastChangeset
        {
            get
            {
                return ((DvcsScriptRepositoryBase.ChangesetId)(this["LastChangeset"]));
            }
            set
            {
                this["LastChangeset"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public DvcsScriptRepositoryBase.Tag LastTag
        {
            get
            {
                return ((DvcsScriptRepositoryBase.Tag)(this["LastTag"]));
            }
            set
            {
                this["LastTag"] = value;
            }
        }
    }
}
