using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZocBuild.Database.Errors
{
    /// <summary>
    /// Represents an error caused by a failure to parse the content of the script file.
    /// </summary>
    public class SqlParseError : BuildErrorBase
    {
        /// <summary>
        /// Creates an instance of a SQL parse error object.
        /// </summary>
        /// <param name="message">The message generated by the SQL parser.</param>
        public SqlParseError(string message)
        {
            Message = message;
        }

        /// <summary>
        /// Gets the message generated by the SQL parser.
        /// </summary>
        public string Message { get; private set; }

        /// <summary>
        /// Gets the display name of the error type.
        /// </summary>
        public override string ErrorType
        {
            get { return "SQL Parse Failure"; }
        }

        /// <summary>
        /// Returns the message for this error.
        /// </summary>
        /// <returns>The error message.</returns>
        public override string GetMessage()
        {
            return Message;
        }

        /// <summary>
        /// Gets the status for which this error corresponds.
        /// </summary>
        public override BuildItem.BuildStatusType Status
        {
            get { return BuildItem.BuildStatusType.ScriptError; }
        }
    }
}
