using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZocBuild.Database.Exceptions
{
    /// <summary>
    /// An exception raised when a script could not be parsed.
    /// </summary>
    public class SqlParseException : Exception
    {
        /// <summary>
        /// Creates an instance of the sql parse exception.
        /// </summary>
        /// <param name="message">The message generated by the SQL parser.</param>
        public SqlParseException(string message)
            : base(message)
        {
            
        }
    }
}
